name: Build artifact

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        docker build --build-arg=HOST=x86_64 -t builder .
        docker run --rm -w $PWD -v $PWD:$PWD builder cp /usr/local/bin/tmux .
    - name: Archive the build artifact
      uses: actions/upload-artifact@v3
      with:
        name: tmux-x86_64
        path: tmux
  build-linux-aarch64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        docker build --build-arg=HOST=aarch64 -t builder .
        docker run --rm -w $PWD -v $PWD:$PWD builder cp /usr/local/bin/tmux .
    - name: Archive the build artifact
      uses: actions/upload-artifact@v3
      with:
        name: tmux-aarch64
        path: tmux
